name: Code Checker

on:
  push:
    branches:
      - main
      - feature 
  pull_request:
    branches:
      - main
      - feature 

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          echo " Installing required packages"
          # sudo apt update -y
          sudo apt install -y nodejs
          sudo apt install -y npm
          npm install inquirer -g
          npm install eslint
          npm install mocha --save-dev

      - name: Run code linting (eslint) 
        run: |
          echo "Run code linting..."
          npm run lint
          # If your commands fail (exit with a non-zero code), the job will automatically fail.

      - name: Run unit tests (mocha)
        run: |
          echo "Run unit tests..."
          npm test
          echo "Code check complete."
          # If your commands fail (exit with a non-zero code), the job will automatically fail.

      - name: Report status
        # This step runs only if the previous steps succeeded (default behavior)
        run: echo "All checks passed successfully!"
        if: success()

      - name: Handle failure
        # This step runs only if a previous step failed
        run: echo "Code checks failed. Please review the errors above."
        if: failure()

